### ISSUE TITLE
It's not possible to configure pytest-echo using pytest.ini

### ISSUE THREAD

**Issue by thedrow** [pytest-dev/pytest-echo#1]
We need to add ini options like https://github.com/pytest-dev/pytest-django/blob/master/pytest_django/plugin.py#L61

**Comment by saxix** [comment]
not sure to get the problem. I currently configure pytest-echo via .ini. What is the relation with the link in your post ?

**Comment by thedrow** [comment]
This is the API to add ini options to pytest.ini.
It's not clear how you configure your pytest.ini to print envars or dependencies or anything else.
The example in the readme file doesn't work.

**Comment by saxix** [comment]
you are right, the example is missing the argument (`addopts`). try this

```
[pytest]
addopts =
        -vvv
        --echo-env PWD
        --echo-env DJANGO_SETTINGS_MODULE
        --echo-env VIRTUAL_ENV
        --echo-version django
        --echo-version pip
        --echo-attr django.conf.settings.DATABASES.default.ENGINE
        --echo-attr django.conf.settings._wrapped.SETTINGS_MODULE
```

**Comment by thedrow** [comment]
Yup. That does it.
It would still be better if there was an option to use the ini configuration directly.
